nexus:
  image: "sonatype/nexus:2.11.4-01"
  ports:
    - "18081:8081"

jenkins:
  image: "lidicalso/jenkins:1.642.1"
  ports:
    - "18080:8080"
  links:
    - nexus:nexus
    - gitlab:gitlab
    - sonar:sonar

sonar:
  image: sonarqube:4.5.6
  ports:
    - "19000:9000"
    - "19092:9092"
  links:
    - sonardb:sonardb
  environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
sonardb:
  image: "postgres:9.4.5"
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - DB_NAME=sonar
gitlab:
  image: sameersbn/gitlab:8.4.2
  links:
    - redis:redisio
    - gitlabdb:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - TZ=Europe/Berlin
    - GITLAB_TIMEZONE=Berlin
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_HOST=localhost
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false
    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com
    - GITLAB_BACKUPS=daily
    - GITLAB_BACKUP_TIME=01:00
    - GITLAB_BUILDS_DIR=/home/git/data/blds
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - "/opt/docker/gitlab/gitlab:/home/git/data"
redis:
  image: "sameersbn/redis:latest"
  volumes:
    - "/opt/docker/gitlab/redis:/var/lib/redis"
gitlabdb:
  image: "sameersbn/postgresql:9.4-8"
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - "/opt/docker/postgres/data:/var/lib/postgresql"